version: "3.9"

services:
  donkey-sim:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "9091:9091"  # Port för simulator-kommunikation med lokal Python-kod
    stdin_open: true
    tty: true
